### ISSUE TITLE
OFAC: Invalid address

### ISSUE THREAD

**Issue by wjmelements** [flashbots/mev-relay-js#41]
`'0xa7e5d5a720f06526557c513402f2e6b5fa20b00'` is too short to be a valid address.

**Comment by jparyani** [comment]
I do agree that's an invalid address, but I triple checked and that's what they give as an address. See https://www.treasury.gov/ofac/downloads/sdnlist.txt

**Comment by chris124567** [comment]
Correct address: https://etherscan.io/address/0xa7e5d5a720f06526557c513402f2e6b5fa20b008 (see https://www.elliptic.co/blog/four-compliance-takeaways-from-blockchain-insights-one-million-russian-troll-farms-influence-us-election)
