### ISSUE TITLE
collect signing keys from miners

### ISSUE THREAD

**Issue by thegostep** [flashbots/mev-relay-js#55]
Need to define a process for distributing relay access keys to miners

**Comment by fiiiu** [comment]
We moved to [Ethereum signatures](https://github.com/flashbots/mev-relay-js/issues/56) so we'll only be collecting miner Ethereum addresses.

Address collection [process](https://hackmd.io/JFrVJaukRjmtF0XpLz4SDA?view) (sharable with miners).

Address checking and tracking added in the [adoption spreadsheet](https://docs.google.com/spreadsheets/d/1FqiLaE4nb37a1z_qK8HM3EhQOnek8brMkN12lveUxJQ/edit#gid=1497694400).

**Comment by pgebheim** [comment]
@thegostep @fiiiu -- Can this be closed or is there something else actionable here?

**Comment by thegostep** [comment]
Can close
