### ISSUE TITLE
The relay response for `eth_sendBundle` doesn't return the same json types

### ISSUE THREAD

**Issue by krasi-georgiev** [flashbots/mev-relay-js#66]
the reply from the relay seems quite strange - when it sends the bundle to the miners it returns
```
{
    "id": 1337,
    "jsonrpc": "2.0",
    "result": true
}
```

but when it doesn't send the bundle to the miners it returns

```
{"jsonrpc":"2.0","id":1,"result":{"bundleHash":"0x4cd3b......"}}
```

To me it makes more sense that the reply is always of the same type. I mean otherwise, it makes it difficult to know how to parse the result.

**Comment by jparyani** [comment]
Can you post an example body that triggers the `"result": true` case? We're struggling to reproduce this issue.

**Comment by krasi-georgiev** [comment]
It happens only occasionally so not sure how I can give you an exact replicable steps, but will try

But looking at your docs even there it indicates that it returns true when it gets accepted by the node 
https://docs.flashbots.net/flashbots-auction/miners/mev-geth-spec/v04-rpc

but then the example shows that the reply returns a different json structure with a string for `bundleHash`

https://docs.flashbots.net/flashbots-auction/searchers/advanced/rpc-endpoint

Could you first comment on this inconsistency as well?

**Comment by jparyani** [comment]
Ah, that’s just the docs being out of date. An older version of the api used to return `result=true`

**Comment by krasi-georgiev** [comment]
ok got it , will try to dig deeper how to replicate

**Comment by krasi-georgiev** [comment]
ok it turns out that it was the ethermine mev endpoint.

Can you confirm if `{"jsonrpc":"2.0","id":1,"result":{"bundleHash":"0x4cd3b......"}}` should be the correct reply so that I can ask the ethermine team to update their api.
